using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Icms.Application.DTOs;
using Icms.Application.Interfaces;
using Icms.Domain.Entities;
using Icms.Infrastructure.Persistence;

namespace Icms.Api.Controllers.V1;

[Authorize]
[ApiController]
[Route("api/districts/{districtId:long}/churches")]
[Tags("Churches")]
[Produces("application/json")]
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
public class ChurchesController(
    IChurchService churchService,
    IAuthorizationService authorizationService,
    IcmsDbContext db,
    LinkGenerator linkGenerator) : ControllerBase
{
    [HttpPost]
    [ProducesResponseType(typeof(CreateChurchResponseDto), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [EndpointSummary("Create a new church")]
    [EndpointDescription("Creates a church under the district together with the church admin account. The admin email and a temporary password are generated by the system and returned once. Admin or the district president only. Returns 409 if the church code already exists.")]
    public async Task<IActionResult> CreateChurch(
        long districtId, CreateChurchRequest request, CancellationToken ct)
    {
        var district = await db.Districts.AsNoTracking()
            .FirstOrDefaultAsync(d => d.Id == districtId && !d.IsDeleted, ct);

        if (district == null)
        {
            return NotFound(new ProblemDetails { Title = "District not found." });
        }

        var authResult = await authorizationService.AuthorizeAsync(User, district, "CanManageDistrict");
        if (!authResult.Succeeded)
        {
            return Forbid();
        }

        var result = await churchService.CreateChurchAsync(districtId, request, ct);

        return result.Match<IActionResult>(
            response => CreatedAtAction(nameof(GetChurchById),
                new { districtId, churchId = response.Church.Id }, response),
            error => error.ToResult(Request));
    }

    [HttpGet]
    [ProducesResponseType(typeof(PagedResponse<ChurchResponseDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("List churches of a district")]
    [EndpointDescription("Paged list of churches in the district, searchable by name or code. Returns 404 if the district does not exist.")]
    public async Task<IActionResult> GetChurches(
        long districtId, [FromQuery] PagedRequest paging, CancellationToken ct)
    {
        var result = await churchService.GetChurchesAsync(districtId, paging, ct);

        return result.Match<IActionResult>(
            page => Ok(page),
            error => error.ToResult(Request));
    }

    [HttpGet("{churchId:long}", Name = nameof(GetChurchById))]
    [ProducesResponseType(typeof(ChurchDetailDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Get church by ID")]
    [EndpointDescription("Returns the church with its daughter and member counts.")]
    public async Task<IActionResult> GetChurchById(
        long districtId, long churchId, CancellationToken ct)
    {
        var result = await churchService.GetChurchDetailAsync(churchId, ct);

        return result.Match<IActionResult>(
            church => Ok(church with { Links = BuildLinks(districtId, church.Id) }),
            error => error.ToResult(Request));
    }

    [HttpPut("{churchId:long}", Name = nameof(UpdateChurch))]
    [ProducesResponseType(typeof(ChurchResponseDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [EndpointSummary("Update a church")]
    [EndpointDescription("Updates the editable fields of a church. Admin or the district president only (church admins cannot edit or delete their church). Type and parent can only change via the upgrade workflow. Returns 409 if the new code belongs to another church.")]
    public async Task<IActionResult> UpdateChurch(
        long districtId, long churchId, UpdateChurchRequest request, CancellationToken ct)
    {
        var authResult = await AuthorizeManageDistrictForChurchAsync(churchId, ct);
        if (authResult is not null)
        {
            return authResult;
        }

        var result = await churchService.UpdateChurchAsync(churchId, request, ct);

        return result.Match<IActionResult>(
            church => Ok(church),
            error => error.ToResult(Request));
    }

    [HttpPost("{churchId:long}/admins", Name = nameof(AddChurchAdmin))]
    [ProducesResponseType(typeof(CreateChurchResponseDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [EndpointSummary("Add a church admin (sub-admin)")]
    [EndpointDescription("Creates an additional ChurchAdmin account for this church with a system-generated email and temporary password, plus an employee record. Admin or the church's admin only.")]
    public async Task<IActionResult> AddChurchAdmin(
        long districtId, long churchId, AddChurchAdminRequest request, CancellationToken ct)
    {
        var authResult = await AuthorizeManageChurchAsync(churchId, ct);
        if (authResult is not null)
        {
            return authResult;
        }

        var result = await churchService.AddChurchAdminAsync(churchId, request, ct);

        return result.Match<IActionResult>(
            response => Ok(response),
            error => error.ToResult(Request));
    }

    [HttpDelete("{churchId:long}", Name = nameof(DeleteChurch))]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [EndpointSummary("Delete a church")]
    [EndpointDescription("Soft-deletes a church. Admin or the district president only. Returns 409 if the church has daughter churches or members.")]
    public async Task<IActionResult> DeleteChurch(
        long districtId, long churchId, CancellationToken ct)
    {
        var authResult = await AuthorizeManageDistrictForChurchAsync(churchId, ct);
        if (authResult is not null)
        {
            return authResult;
        }

        var result = await churchService.DeleteChurchAsync(churchId, ct);

        return result.Match<IActionResult>(
            _ => NoContent(),
            error => error.ToResult(Request));
    }

    private async Task<IActionResult?> AuthorizeManageChurchAsync(long churchId, CancellationToken ct)
    {
        var church = await db.Churches.AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == churchId && !c.IsDeleted, ct);

        if (church == null)
        {
            return NotFound(new ProblemDetails { Title = "Church not found." });
        }

        var authResult = await authorizationService.AuthorizeAsync(User, church, "CanManageChurch");
        return authResult.Succeeded ? null : Forbid();
    }

    private async Task<IActionResult?> AuthorizeManageDistrictForChurchAsync(long churchId, CancellationToken ct)
    {
        var church = await db.Churches.AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == churchId && !c.IsDeleted, ct);

        if (church == null)
        {
            return NotFound(new ProblemDetails { Title = "Church not found." });
        }

        var district = await db.Districts.AsNoTracking()
            .FirstOrDefaultAsync(d => d.Id == church.DistrictId, ct);

        if (district == null)
        {
            return NotFound(new ProblemDetails { Title = "District not found." });
        }

        var authResult = await authorizationService.AuthorizeAsync(User, district, "CanManageDistrict");
        return authResult.Succeeded ? null : Forbid();
    }

    private IReadOnlyList<LinkDto> BuildLinks(long districtId, long churchId)
    {
        var path = (string routeName, object values) =>
            linkGenerator.GetPathByName(HttpContext, routeName, values)!;

        return
        [
            new(path(nameof(GetChurchById), new { districtId, churchId }), "self", "GET"),
            new(path(nameof(UpdateChurch), new { districtId, churchId }), "update", "PUT"),
            new(path(nameof(DeleteChurch), new { districtId, churchId }), "delete", "DELETE")
        ];
    }
}