using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Icms.Application.DTOs;
using Icms.Application.Interfaces;

namespace Icms.Api.Controllers.V1;

[Authorize]
[ApiController]
[Route("api/members")]
[Tags("Members")]
[Produces("application/json")]
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
public class MembersController(
    IMemberService memberService,
    LinkGenerator linkGenerator) : ControllerBase
{
    [HttpPost]
    [ProducesResponseType(typeof(MemberResponseDto), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [EndpointSummary("Register a new member")]
    [EndpointDescription("Registers a member under a church. The EFGBC ID is generated by the system.")]
    public async Task<IActionResult> RegisterMember(
        CreateMemberRequest request, CancellationToken ct)
    {
        var result = await memberService.RegisterMemberAsync(request, ct);

        return result.Match<IActionResult>(
            member => CreatedAtAction(nameof(GetMemberById), new { id = member.Id },
                member with { Links = BuildLinks(member.Id) }),
            error => error.ToResult(Request));
    }

    [HttpGet]
    [ProducesResponseType(typeof(PagedResponse<MemberResponseDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("List members")]
    [EndpointDescription("Paged list of members, optionally filtered by church. Returns 404 if the church does not exist.")]
    public async Task<IActionResult> GetMembers(
        [FromQuery] long? churchId, [FromQuery] PagedRequest paging, CancellationToken ct)
    {
        var result = await memberService.GetMembersAsync(churchId, paging, ct);

        return result.Match<IActionResult>(
            page => Ok(page),
            error => error.ToResult(Request));
    }

    [HttpGet("stats")]
    [ProducesResponseType(typeof(MemberStatsDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Member statistics")]
    [EndpointDescription("Member counts by status, optionally filtered by church.")]
    public async Task<IActionResult> GetStats(
        [FromQuery] long? churchId, CancellationToken ct)
    {
        var result = await memberService.GetMemberStatsAsync(churchId, ct);

        return result.Match<IActionResult>(
            stats => Ok(stats),
            error => error.ToResult(Request));
    }

    [HttpGet("{id:long}/account", Name = nameof(GetMemberAccount))]
    [ProducesResponseType(typeof(MemberAccountInfoDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Member login account")]
    [EndpointDescription("Whether the member already has a login account and which email it uses. The password is never revealed here.")]
    public async Task<IActionResult> GetMemberAccount(long id, CancellationToken ct)
    {
        var result = await memberService.GetMemberAccountAsync(id, ct);

        return result.Match<IActionResult>(
            account => Ok(account),
            error => error.ToResult(Request));
    }

    [HttpPost("{id:long}/account", Name = nameof(IssueCredentials))]
    [ProducesResponseType(typeof(IssueMemberCredentialsDto), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(IssueMemberCredentialsDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Issue member login credentials")]
    [EndpointDescription("Creates (or reuses) the member's login account and returns the temporary password only when the account was just created.")]
    public async Task<IActionResult> IssueCredentials(long id, CancellationToken ct)
    {
        var result = await memberService.IssueCredentialsAsync(id, ct);

        return result.Match<IActionResult>(
            account => account.TempPassword is null
                ? Ok(account)
                : CreatedAtAction(nameof(GetMemberAccount), new { id = id }, account),
            error => error.ToResult(Request));
    }

    [HttpGet("{id:long}", Name = nameof(GetMemberById))]
    [ProducesResponseType(typeof(MemberResponseDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Get member by ID")]
    public async Task<IActionResult> GetMemberById(long id, CancellationToken ct)
    {
        var result = await memberService.GetMemberByIdAsync(id, ct);

        return result.Match<IActionResult>(
            member => Ok(member with { Links = BuildLinks(member.Id) }),
            error => error.ToResult(Request));
    }

    [HttpPut("{id:long}", Name = nameof(UpdateMember))]
    [ProducesResponseType(typeof(MemberResponseDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Update a member")]
    [EndpointDescription("Updates the editable fields of a member. Church, EFGBC ID and status change only via their dedicated workflows.")]
    public async Task<IActionResult> UpdateMember(
        long id, UpdateMemberRequest request, CancellationToken ct)
    {
        var result = await memberService.UpdateMemberAsync(id, request, ct);

        return result.Match<IActionResult>(
            member => Ok(member with { Links = BuildLinks(member.Id) }),
            error => error.ToResult(Request));
    }

    [HttpDelete("{id:long}", Name = nameof(DeleteMember))]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [EndpointSummary("Delete a member")]
    [EndpointDescription("Soft-deletes a member. The EFGBC ID is never reused.")]
    public async Task<IActionResult> DeleteMember(long id, CancellationToken ct)
    {
        var result = await memberService.DeleteMemberAsync(id, ct);

        return result.Match<IActionResult>(
            _ => NoContent(),
            error => error.ToResult(Request));
    }

    private IReadOnlyList<LinkDto> BuildLinks(long id)
    {
        var path = (string routeName, object values) =>
            linkGenerator.GetPathByName(HttpContext, routeName, values)!;

        return
        [
            new(path(nameof(GetMemberById), new { id }), "self", "GET"),
            new(path(nameof(UpdateMember), new { id }), "update", "PUT"),
            new(path(nameof(DeleteMember), new { id }), "delete", "DELETE")
        ];
    }
}